"""Centralized user-facing strings for island UI modules."""

from __future__ import annotations

from html import escape

APP_TITLE = "设置"

WINDOW_SETTINGS = "设置"
WINDOW_MINIMIZE = "最小化"
WINDOW_MAXIMIZE = "最大化"
WINDOW_RESTORE = "还原"
WINDOW_CLOSE = "关闭"

ROUTE_RENAME = "重命名"
ROUTE_DELETE = "删除"
ROUTE_NOTES = "查看/修改"
ROUTE_OPEN_FILE_LOCATION = "打开文件位置"
ROUTE_RENAME_PLACEHOLDER = "输入路线名称..."
ROUTE_RENAME_CONFIRM = "确认重命名"
ROUTE_RENAME_CANCEL = "取消重命名"
ROUTE_ADD_CATEGORY = "新增类别"
ROUTE_ADD_CATEGORY_PLACEHOLDER = "输入类别名称..."
ROUTE_ADD_CATEGORY_CONFIRM = "确认创建类别"
ROUTE_ADD_CATEGORY_CANCEL = "取消新增类别"
ROUTE_LIST_TITLE = "路线列表"
ROUTE_LIST_REFRESH = "刷新列表"
ROUTE_LIST_REFRESH_TOOLTIP = "重新读取 routes 文件夹下的所有路径"
ROUTE_ADD_CATEGORY_TOOLTIP = "新增一个路线类别文件夹"
ROUTE_TRACKED_TITLE = "当前追踪路线"
ROUTE_TRACKED_JUMP_NODE_TOOLTIP = "跳转到路线节点"
ROUTE_TRACKED_JUMP_EMPTY_TITLE = "无法跳转路线节点"
ROUTE_TRACKED_JUMP_EMPTY_BODY = "这条路线没有可用节点。"
ROUTE_TRACKED_JUMP_TO_NODE_FMT = "已跳转到第 {index} 个节点"
ROUTE_TRACKED_JUMP_COMPLETED_FMT = "路线已完成，已显示第 {index} 个节点"
ROUTE_EMPTY_TRACKED = "暂无已选择路线"
ANNOTATION_ROUTE_HINT = "标注数据来源于17173地图,感谢17173的地图标注工作者们"
ANNOTATION_SOURCE_LINKS = (("17173地图", "https://map.17173.com/rocom/maps/shijie"),)
ANNOTATION_ROUTE_HINT_COMPACT = "右键标注规划不代表实际最优"
ANNOTATION_PLAN_ROUTE = "生成点位最优路线"
ANNOTATION_PLAN_ROUTE_SUCCESS_FMT = "已生成路线“{name}”"
ANNOTATION_PLAN_ROUTE_EMPTY_TITLE = "无法生成路线"
ANNOTATION_PLAN_ROUTE_EMPTY_BODY = "标注“{name}”没有可用采集点位。"
ANNOTATION_PLAN_ROUTE_FAILED_TITLE = "生成路线失败"
ANNOTATION_PLAN_ROUTE_FAILED_BODY_FMT = "未能生成标注“{name}”的路线：{error}"
ANNOTATION_REFRESH_POINTS = "拉取标注"
ANNOTATION_REFRESH_POINTS_TOOLTIP = "拉取 17173 图标和标注点位"
ANNOTATION_REFRESH_CONFIRM_TITLE = "重新拉取标注点位"
ANNOTATION_REFRESH_CONFIRM_BODY = "此操作会重新拉取图标和标注点位，并覆盖 tools/points_all/points.json。你手动添加、更改或删除的标注点位会被重置。确定继续吗？"
ANNOTATION_REFRESH_CONFIRM = "重新拉取"
ANNOTATION_REFRESH_RUNNING = "正在重新拉取图标和标注点位..."
ANNOTATION_REFRESH_SUCCESS = "标注图标和点位已重新拉取"
ANNOTATION_REFRESH_FAILED_TITLE = "重新拉取失败"
ANNOTATION_REFRESH_FAILED_BODY_FMT = "未能重新拉取标注图标和点位。退出码：{code}。{error}"
SETTINGS_AI_DISABLED_MESSAGE = "SIFT方案目前效果可以，暂不接入AI方案。"
ROUTE_DELETE_TITLE = "删除路线"
ROUTE_DELETE_MESSAGE = "确认删除路线“{name}”吗？"
ROUTE_DELETE_CONFIRM = "删除"
ROUTE_DELETE_CANCEL = "取消"
ROUTE_NOTES_TITLE = "路线说明"
ROUTE_NOTES_PLACEHOLDER = "可以为这条路线补充说明、提示或注意事项..."
ROUTE_NOTES_CONFIRM = "确认修改"
ROUTE_NOTES_CANCEL = "取消修改"
ROUTE_NOTES_SAVED = "已保存路线“{name}”的说明和颜色"
ROUTE_NOTES_SAVE_FAILED = "保存路线“{name}”的说明和颜色失败"
ROUTE_NOTES_NOTES_LABEL = "路线说明"
ROUTE_NOTES_COLOR_LABEL = "路线颜色"
ROUTE_NOTES_COLOR_PICK = "选择路线颜色"
ROUTE_NOTES_COLOR_RESET = "跟随全局"
ROUTE_NOTES_COLOR_FOLLOW = "跟随全局颜色"
ROUTE_NOTES_COLOR_CUSTOM = "自定义颜色"
ROUTE_NOTES_COLOR_FOLLOW_TOOLTIP = "当前跟随全局颜色：开启多路线随机颜色时使用路线稳定随机色，关闭时使用默认颜色；点击可为此路线单独选色。"
ROUTE_NOTES_COLOR_CUSTOM_TOOLTIP = "当前使用自定义路线颜色；点击重新选择，确认修改后保存到此路线。"
ROUTE_NOTES_COLOR_RESET_TOOLTIP = "清除此路线的自定义颜色，改为跟随全局颜色；需要点击确认修改后生效。"
ROUTE_NOTES_STATS_TITLE = "节点统计"
ROUTE_NOTES_NODE_LIST = "路线节点"
ROUTE_NOTES_NODE_EMPTY = "这条路线还没有节点。"
ROUTE_NOTES_NODE_COLLECT = "采集点"
ROUTE_NOTES_NODE_TELEPORT = "传送点"
ROUTE_NOTES_NODE_GUIDE = "引路点"
ROUTE_OPEN_FILE_LOCATION_FAILED = "无法打开路线“{name}”的文件位置"
ROUTE_RENAME_EMPTY = "路线名称不能为空"
ROUTE_RENAME_INVALID = "名称无效或已存在"
ROUTE_CATEGORY_EMPTY = "类别名称不能为空"
ROUTE_CATEGORY_INVALID = "名称不能包含 / 或 \\"
ROUTE_CATEGORY_RENAME = "重命名分类"
ROUTE_CATEGORY_DELETE = "删除分类"
ROUTE_CATEGORY_OPEN_FILE_LOCATION = "打开分类文件位置"
ROUTE_CATEGORY_RENAME_TITLE = "重命名分类"
ROUTE_CATEGORY_RENAME_PLACEHOLDER = "输入分类名称..."
ROUTE_CATEGORY_RENAME_CONFIRM = "确认重命名"
ROUTE_CATEGORY_RENAME_CANCEL = "取消重命名"
ROUTE_CATEGORY_DELETE_TITLE = "删除分类"
ROUTE_CATEGORY_DELETE_MESSAGE = "确认删除分类“{name}”吗？\n\n该分类下的所有路线和文件都将被删除。"
ROUTE_CATEGORY_DELETE_CONFIRM = "删除"
ROUTE_CATEGORY_DELETE_CANCEL = "取消"
ROUTE_CATEGORY_RENAME_EMPTY = "分类名称不能为空"
ROUTE_CATEGORY_RENAME_INVALID = "分类名称无效或已存在"
ROUTE_CATEGORY_OPEN_FILE_LOCATION_FAILED = "无法打开分类“{name}”的文件位置"

ROUTE_DRAWING_MENU_LABEL = "纯净绘制"
ROUTE_DRAWING_TITLE = "纯净绘制"
ROUTE_DRAWING_MODE_REQUIRED = "请在暂停或最大化窗口状态下绘制"
ROUTE_DRAWING_ROUTE_MISSING = "未能找到这条路线，请刷新路线列表后重试。"
ROUTE_DRAWING_ENTERED_FMT = "已进入纯净绘制：{name}"
ROUTE_DRAWING_STATE_FMT = "纯净绘制中：{name}"
ROUTE_DRAWING_TOOLBAR_TITLE = "纯净绘制工具栏"
ROUTE_DRAWING_END = "结束绘制"
ROUTE_DRAWING_SAVE = "保存绘制"
ROUTE_DRAWING_PAUSE = "暂停绘制"
ROUTE_DRAWING_RESUME = "继续绘制"
ROUTE_DRAWING_UNDO = "撤销"
ROUTE_DRAWING_CLEAR = "清空"
ROUTE_DRAWING_HIDE_OTHER_ROUTES = "隐藏追踪路线"
ROUTE_DRAWING_NODE_COLLECT = "采集点"
ROUTE_DRAWING_NODE_TELEPORT = "传送点"
ROUTE_DRAWING_NODE_VIRTUAL = "空节点"
ROUTE_DRAWING_INSERT_AT_END = "插入在最后"
ROUTE_DRAWING_LOOP = "闭环路径"
ROUTE_DRAWING_ADD_ANNOTATION = "同时添加标注"
ROUTE_DRAWING_SAME_ANNOTATION_TYPE = "标注同类型"
ROUTE_DRAWING_SELECT_ANNOTATION_TYPE = "选择标注类型"
ROUTE_DRAWING_SELECT_ANNOTATION_FIRST = "请先选择标注类型"
ROUTE_DRAWING_SAVE_FAILED_TITLE = "保存绘制失败"
ROUTE_DRAWING_SAVE_FAILED_BODY = "未能写入路线文件，请查看日志。"
ROUTE_DRAWING_SAVED_FMT = "已保存纯净绘制：{name}"
ROUTE_DRAWING_EXIT_TITLE = "退出纯净绘制"
ROUTE_DRAWING_EXIT_UNSAVED_BODY = "当前绘制尚未保存，要先保存这次修改吗？"
ROUTE_DRAWING_EXIT_DISCARD = "放弃"
ROUTE_DRAWING_EXIT_CANCEL = "取消"
ROUTE_DRAWING_EXIT_SAVE = "保存"
ROUTE_DRAWING_HELP_TITLE = "纯净绘制说明"
ROUTE_DRAWING_HELP_BODY = (
    "左键单点击地图会添加节点；按住草稿节点可直接拖动调整位置；拖动空白地图仍用于平移地图。\n\n"
    "开启“插入在最后”时，新节点会追加到当前路线末尾；关闭后，新节点会插入到距离点击位置最近的草稿节点后面。\n\n"
    "工具栏可切换采集点、传送点、空节点。绘制预览线始终为白色：采集点为实线，传送点为虚线，空节点为点线。\n\n"
    "开启“闭环路径”后，最后一个节点会连回第一个节点；点击“保存绘制”后会写入路线的 loop 字段。\n\n"
    "“同时添加标注”用于在新增路线节点时顺手为该节点写入点位标注；关闭时只新增路线节点。开启后若不启用“标注同类型”，每次加点都会弹出标注选择窗口。\n\n"
    "开启“标注同类型”后，会直接使用“选择标注类型”里选好的统一标注类型，适合连续绘制同类采集点；如果未先选择类型，会提示后不添加节点。\n\n"
    "右键草稿节点可以添加/修改标注、删除标注或删除节点；这些操作只修改草稿，点击“保存绘制”后才写入路线文件。\n\n"
    "“撤销”或 Ctrl+Z 会撤销上一步新增、删除、清空、移动或标注修改。“结束绘制”会在未保存时询问保存、放弃或取消。"
)

HEADER_RELOCATE = "重定位"
HEADER_RESET_VIEW = "重置视图"
HEADER_HIDE_SIDEBAR = "隐藏侧边栏"
HEADER_SHOW_SIDEBAR = "展开侧边栏"
HEADER_START_NAV = "开始导航"
HEADER_TERMINATE = "终止导航"
HEADER_LOCK = "锁定"
HEADER_UNLOCK = "解锁"
HEADER_UNLOCK_HINT = "快捷键 Alt+` 解锁"

MAP_HINT = "滚轮缩放，左键拖动，双击选点"

INSERT_POINT_DIALOG_TITLE = "添加节点到路线"
INSERT_POINT_COORD_FMT = "坐标：X = {x}，Y = {y}"
INSERT_POINT_ROUTES_LABEL = "目标路线（勾选要插入的）："
INSERT_POINT_SUGGEST_FMT = "建议 {pos}/{total}"
INSERT_POINT_POSITION_LABEL = "位置："
INSERT_POINT_CONFIRM = "确认插入"
INSERT_POINT_CANCEL = "取消"
INSERT_POINT_NO_SELECTION = "请至少勾选一条路线"
INSERT_POINT_MULTI_WARN_TITLE = "多路线插入提示"
INSERT_POINT_MULTI_WARN_BODY = "多条路线同时插入会按各路线当前填写的位置写入，默认值为算法建议；请确认每条路线的插入位置后再继续。"
INSERT_POINT_SUCCESS_FMT = "已向 {count} 条路线插入节点"
INSERT_POINT_PARTIAL_FMT = "已插入 {ok} 条，失败 {fail} 条"
INSERT_POINT_FAIL_TITLE = "插入失败"
INSERT_POINT_FAIL_BODY = "未能写入任何路线文件，请查看日志。"
INSERT_POINT_EMPTY_TITLE = "无追踪路线"
INSERT_POINT_EMPTY_BODY = "请先在侧边栏勾选至少一条路线后再添加节点。"

MAP_ADD_ANNOTATION_MENU_LABEL = "添加标注"
MAP_ADD_POINT_MENU_LABEL = "添加节点"
MAP_ADD_POINT_WITH_ANNOTATION_MENU_LABEL = "添加节点并绑定标注"
MAP_ADD_ANNOTATION_SUCCESS_FMT = "已添加标注“{name}”"
MAP_ADD_ANNOTATION_FAIL_TITLE = "添加标注失败"
MAP_ADD_ANNOTATION_FAIL_BODY = "未能写入标注点位，请查看日志。"

DELETE_POINT_MENU_LABEL = "删除此节点"
ADD_POINT_ANNOTATION_MENU_LABEL = "增加标注"
CHANGE_POINT_ANNOTATION_MENU_LABEL = "更改标注"
DELETE_POINT_ANNOTATION_MENU_LABEL = "删除标注"
CHANGE_POINT_NODE_TYPE_MENU_LABEL = "更改节点类型"
ANNOTATION_TYPE_PICKER_TITLE = "选择节点标注"
ANNOTATION_TYPE_PICKER_EMPTY = "未找到可用标注，请先生成标注文件 tools/points_all/points.json"
ANNOTATION_TYPE_PICKER_CANCEL = "取消"
POINT_ANNOTATION_SUCCESS_FMT = "已更新节点标注为“{name}”"
POINT_ANNOTATION_DELETE_SUCCESS = "已删除节点标注"
POINT_ANNOTATION_FAIL_TITLE = "标注更新失败"
POINT_ANNOTATION_FAIL_BODY = "未能写入路线节点标注，请查看日志。"
POINT_ANNOTATION_DELETE_FAIL_BODY = "未能删除节点标注，请查看日志。"
POINT_NODE_TYPE_SUCCESS_FMT = "已更新节点类型为“{name}”"
POINT_NODE_TYPE_FAIL_TITLE = "节点类型更新失败"
POINT_NODE_TYPE_FAIL_BODY = "未能写入路线节点类型，请查看日志。"
UNDO_ROUTE_POINT_MOVE_MENU_LABEL = "撤销节点移动（Ctrl+Z）"
POINT_MOVE_SUCCESS = "节点位置已更新，可 Ctrl+Z 撤销"
POINT_MOVE_UNDO_SUCCESS = "已撤销节点移动"
POINT_MOVE_FAIL_TITLE = "节点移动失败"
POINT_MOVE_FAIL_BODY = "未能写入路线节点位置，请查看日志。"
MAP_CHANGE_ANNOTATION_MENU_LABEL = "更改标注"
MAP_ADD_ANNOTATION_TO_ROUTE_MENU_LABEL = "添加标注到路线"
MAP_DELETE_ANNOTATION_MENU_LABEL = "删除标注"
MAP_ANNOTATION_CHANGE_SUCCESS_FMT = "已更改标注为“{name}”"
MAP_ANNOTATION_DELETE_TITLE = "删除标注"
MAP_ANNOTATION_DELETE_BODY = "确认删除此标注点位吗？"
MAP_ANNOTATION_DELETE_SUCCESS = "已删除标注点位"
MAP_ANNOTATION_FAIL_TITLE = "标注操作失败"
MAP_ANNOTATION_CHANGE_FAIL_BODY = "未能更改标注点位，请查看日志。"
MAP_ANNOTATION_DELETE_FAIL_BODY = "未能删除标注点位，请查看日志。"
MAP_ANNOTATION_ROUTE_FAIL_BODY = "未能读取此标注点位，请查看日志。"
MARK_POINT_VISITED_MENU_LABEL = "标记已到"
MARK_POINT_UNVISITED_MENU_LABEL = "标记未到"
DELETE_POINT_TITLE = "删除节点"
DELETE_POINT_SINGLE_BODY_FMT = "确认删除路线“{name}”的第 {pos} 个节点吗？"
DELETE_POINT_MULTI_SINGLE_ROUTE_FMT = "确认删除路线“{name}”的 {count} 个节点吗？"
DELETE_POINT_MULTI_ROUTES_FMT = "确认删除 {routes} 条路线上共 {count} 个节点吗？"
DELETE_POINT_CONFIRM = "删除"
DELETE_POINT_CANCEL = "取消"
DELETE_POINT_SUCCESS_FMT = "已删除 {count} 个节点"
DELETE_POINT_PARTIAL_FMT = "已删除 {ok} 个，失败 {fail} 个"
DELETE_POINT_FAIL_TITLE = "删除失败"
DELETE_POINT_FAIL_BODY = "未能从任何路线中删除节点，请查看日志。"
SEARCH_PLACEHOLDER = "搜索路线..."

STATE_LOCKED = "定位稳定"
STATE_INERTIAL = "定位暂时不稳定，沿用上一帧位置。"
STATE_SEARCHING = "正在搜索目标，请稍候..."
STATE_PAUSED = "暂停定位"
ALERT_LOST = "目标丢失，正在尝试重新定位。"

MINI_ICON_RESTORE = "还原窗口"
MINI_ICON_CLOSE = "关闭程序"

SETTINGS_SAVED = "设置已应用"
MINIMAP_UPDATED = "小地图区域已更新"
SETTINGS_SAVE_FAILED = "写入 config.json 失败：{error}"
SETTINGS_INVALID_INPUT = "字段 {label} 的值“{value}”无法解析为 {type_name}。"
SETTINGS_INVALID_MINIMAP = "小地图 {key} 的值“{value}”不是有效整数。"
SETTINGS_RESTART_REQUIRED_TITLE = "需要重启"
SETTINGS_RESTART_REQUIRED_MESSAGE = "已保存，但以下参数需要重启应用后才会生效：\n\n  {fields}"

UPDATE_ERROR_FALLBACK_DOWNLOAD_HINT = "长期更新失败可在设置中查看夸克网盘进行完整下载。"
UPDATE_ERROR_CHECK_TITLE = "检查更新失败"
UPDATE_ERROR_INSTALL_TITLE = "更新失败"
UPDATE_ERROR_UNKNOWN = "未知错误。"
UPDATE_ERROR_CHECK_UNKNOWN = "更新检查返回了未知结果。"
UPDATE_ERROR_INSTALL_UNKNOWN = "更新安装返回了未知结果。"
UPDATE_ERROR_NO_MANIFEST_URL = "尚未配置更新源。"
UPDATE_ERROR_ALL_SOURCES_FAILED_FMT = "无法连接所有更新源，请检查网络或稍后重试。已尝试 {count} 个更新源。"
UPDATE_ERROR_SOURCE_CONNECT_FMT = "无法连接更新源：{error}"
UPDATE_ERROR_SOURCE_HTTP_FMT = "更新源返回 HTTP {status_code}。"
UPDATE_ERROR_DOWNLOAD_FAILED_FMT = "下载失败：{error}"
UPDATE_ERROR_DOWNLOAD_HTTP_FMT = "下载失败 HTTP {status_code}: {url}"
UPDATE_ERROR_FILE_HASH_FMT = "文件校验失败：{path}"
UPDATE_ERROR_PLAN_INVALID = "更新计划无效。"
UPDATE_ERROR_RESTART_REQUIRED = "此更新包含程序本体文件，需要重启安装。"
UPDATE_ERROR_MANIFEST_EMPTY = "更新清单为空。"
UPDATE_ERROR_UPDATER_MISSING_FMT = "未找到更新器：{path}"
UPDATE_ERROR_UPDATER_START_FAILED_FMT = "启动更新器失败：{error}"


def annotation_route_hint_html() -> str:
    text = escape(ANNOTATION_ROUTE_HINT)
    for label, url in ANNOTATION_SOURCE_LINKS:
        safe_label = escape(str(label))
        if not safe_label:
            continue
        safe_url = escape(str(url), quote=True)
        text = text.replace(safe_label, f'<a href="{safe_url}">{safe_label}</a>')
    return text


def with_update_error_hint(message: str) -> str:
    text = str(message or UPDATE_ERROR_UNKNOWN).strip() or UPDATE_ERROR_UNKNOWN
    if UPDATE_ERROR_FALLBACK_DOWNLOAD_HINT in text:
        return text
    return f"{text}\n\n{UPDATE_ERROR_FALLBACK_DOWNLOAD_HINT}"

MINIMAP_PREVIEW_TITLE = "确认小地图截取区域"
MINIMAP_RETAKE = "重新截取"
MINIMAP_CONFIRM = "确定"
MINIMAP_SET = "设置小地图"
MINIMAP_OVERLAY_TOP = "左键拖动 | 滚轮缩放"
MINIMAP_OVERLAY_BOTTOM = "按 回车/双击 确认截图"
